/** The page: the form posts JSON to /api/submissions and shows the list it answers with. Classes are Tailwind's, generated by UnoCSS at run time. */
import initUnocssRuntime from "npm:@unocss/runtime@66";
import presetWind4 from "npm:@unocss/preset-wind4@66";
import { render } from "npm:preact";
import { useEffect, useState } from "npm:preact/hooks";

import type { NewSubmission, Submission } from "../shared/types.ts";

initUnocssRuntime({ defaults: { presets: [presetWind4()] } });

const empty: NewSubmission = { name: "", email: "", message: "" };

const input = "border border-neutral-300 rounded px-3 py-2 w-full";

function App() {
  const [draft, setDraft] = useState(empty);
  const [submissions, setSubmissions] = useState<ReadonlyArray<Submission>>([]);
  const [error, setError] = useState<string>();

  useEffect(() => {
    fetch("/api/submissions")
      .then((response) => response.json())
      .then(setSubmissions);
  }, []);

  const submit = async (event: Event) => {
    event.preventDefault();
    const response = await fetch("/api/submissions", {
      method: "POST",
      headers: { "content-type": "application/json" },
      body: JSON.stringify(draft),
    });

    if (!response.ok) return setError(await response.text());

    setSubmissions(await response.json());
    setDraft(empty);
    setError(undefined);
  };

  const field = (name: keyof NewSubmission) => ({
    name,
    value: draft[name],
    required: true,
    class: input,
    onInput: (event: Event) =>
      setDraft({ ...draft, [name]: (event.currentTarget as HTMLInputElement).value }),
  });

  return (
    <main class="max-w-md mx-auto px-4 py-12 font-sans text-neutral-900">
      <h1 class="text-2xl font-bold mb-2">Contact form</h1>
      <p class="text-neutral-600 mb-6">Submissions are saved to this applet's SQLite database.</p>
      <form
        onSubmit={(event) => void submit(event)}
        class="flex flex-col gap-4 bg-white p-6 rounded-lg shadow"
      >
        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium">Name</span>
          <input {...field("name")} />
        </label>
        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium">Email</span>
          <input type="email" {...field("email")} />
        </label>
        <label class="flex flex-col gap-1">
          <span class="text-sm font-medium">Message</span>
          <textarea rows={4} {...field("message")} />
        </label>
        {error && <p class="text-sm text-red-600">{error}</p>}
        <button
          type="submit"
          class="bg-blue-600 text-white rounded px-4 py-2 font-medium hover:bg-blue-700"
        >
          Send
        </button>
      </form>
      <h2 class="text-xl font-bold mt-10 mb-4">Submissions ({submissions.length})</h2>
      {submissions.length === 0 ? (
        <p class="text-neutral-600">Nothing yet. Be the first to submit the form.</p>
      ) : (
        <ul class="flex flex-col gap-4">
          {submissions.map((s) => (
            <li key={s.id} class="bg-white p-4 rounded-lg shadow">
              <div class="flex justify-between gap-2 mb-1">
                <span class="font-medium">{s.name}</span>
                <span class="text-sm text-neutral-500">{s.created_at}</span>
              </div>
              <div class="text-sm text-blue-600 mb-2">{s.email}</div>
              <p class="text-neutral-700 whitespace-pre-wrap">{s.message}</p>
            </li>
          ))}
        </ul>
      )}
    </main>
  );
}

render(<App />, document.getElementById("app")!);
