/** The page: a counter kept in the browser and a greeting fetched from /api/greeting. Classes are Tailwind's, generated by UnoCSS at run time. */
import initUnocssRuntime from "npm:@unocss/runtime@66";
import presetWind4 from "npm:@unocss/preset-wind4@66";
import { render } from "npm:preact";
import { useEffect, useState } from "npm:preact/hooks";

initUnocssRuntime({ defaults: { presets: [presetWind4()] } });

function App() {
  const [count, setCount] = useState(0);
  const [greeting, setGreeting] = useState("…");

  useEffect(() => {
    fetch("/api/greeting")
      .then((response) => response.json())
      .then((body: { greeting: string }) => setGreeting(body.greeting));
  }, []);

  return (
    <main class="max-w-md mx-auto mt-16 px-4 font-sans text-gray-800">
      <h1 class="text-3xl font-bold mb-6">Preact + Hono</h1>
      <p class="mb-6 text-gray-500">{greeting}</p>
      <div class="flex items-center gap-3">
        <span>Clicked</span>
        <button
          class="bg-blue-500 hover:bg-blue-600 text-white font-medium px-4 py-2 rounded-lg cursor-pointer"
          onClick={() => setCount((c) => c + 1)}
        >
          {count}
        </button>
        <span>times</span>
      </div>
    </main>
  );
}

render(<App />, document.getElementById("app")!);
