/** The chat page: the history lives here, and each turn streams from /api/chat into the last message. Classes are Tailwind's, generated by UnoCSS at run time. */
import initUnocssRuntime from "npm:@unocss/runtime@66";
import presetWind4 from "npm:@unocss/preset-wind4@66";
import { marked } from "npm:marked@^15";
import { render } from "npm:preact";
import { useEffect, useRef, useState } from "npm:preact/hooks";

import type { ChatMessage, ChatRequest } from "../shared/chat.ts";
import styles from "./styles.css";

initUnocssRuntime({ defaults: { presets: [presetWind4()] } });

const button =
  "cursor-pointer rounded-xl border border-stone-200 bg-white px-3.5 py-2 text-stone-900 disabled:cursor-default disabled:opacity-40";

const storageKey = "chat-history";

const suggestions = [
  "Explain what a Durable Object is in three sentences",
  "Write a SQL query that finds duplicate emails in a users table",
  "Give me a haiku about a slow build",
];

/** The reply as it streams: the text so far and the handle that stops it. */
type Reply = { readonly text: string; readonly controller: AbortController };

const loadHistory = (): ChatMessage[] => JSON.parse(localStorage.getItem(storageKey) ?? "[]");

/** POSTs the history and feeds every chunk of the reply to `onText`; resolves with the whole reply. */
async function streamReply(
  messages: ReadonlyArray<ChatMessage>,
  signal: AbortSignal,
  onText: (text: string) => void,
): Promise<string> {
  const body: ChatRequest = { messages };
  const response = await fetch("/api/chat", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(body),
    signal,
  });

  if (!response.ok) throw new Error(`the server answered ${response.status}`);

  const reader = response.body!.pipeThrough(new TextDecoderStream()).getReader();
  let text = "";

  for (let part = await reader.read(); !part.done; part = await reader.read()) {
    text += part.value;
    onText(text);
  }

  return text;
}

const Markdown = ({ text }: { text: string }) => (
  <div dangerouslySetInnerHTML={{ __html: marked.parse(text, { async: false }) }} />
);

const dot = "block h-2 w-2 rounded-full bg-stone-500";

const Typing = () => (
  <span class="typing inline-flex gap-1.5 py-2" aria-label="waiting for the answer">
    <i class={dot} />
    <i class={dot} />
    <i class={dot} />
  </span>
);

function Composer({
  busy,
  onSend,
  onStop,
}: {
  busy: boolean;
  onSend: (text: string) => void;
  onStop: () => void;
}) {
  const [draft, setDraft] = useState("");
  const area = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    if (!busy) area.current?.focus();
  }, [busy]);

  const submit = (event: Event) => {
    event.preventDefault();

    if (busy || draft.trim() === "") return;

    onSend(draft.trim());
    setDraft("");
    area.current!.style.height = "auto";
  };

  const grow = (event: Event) => {
    const element = event.currentTarget as HTMLTextAreaElement;
    setDraft(element.value);
    element.style.height = "auto";
    element.style.height = `${element.scrollHeight}px`;
  };

  const keyDown = (event: KeyboardEvent) => {
    if (event.key === "Enter" && !event.shiftKey) submit(event);
  };

  return (
    <div class="border-t border-stone-200 bg-white px-4 py-3">
      <form
        onSubmit={submit}
        class="mx-auto flex max-w-2xl items-end gap-2 rounded-2xl border border-stone-200 bg-stone-50 py-2 pl-3.5 pr-2 focus-within:border-blue-600"
      >
        <textarea
          ref={area}
          rows={1}
          value={draft}
          placeholder="Ask anything"
          disabled={busy}
          onInput={grow}
          onKeyDown={keyDown}
          class="max-h-48 flex-1 resize-none border-0 bg-transparent py-1.5 font-[inherit] text-[inherit] outline-none"
        />
        {busy ? (
          <button type="button" class={`${button} !border-stone-900 !bg-stone-900 !text-white`} onClick={onStop}>
            Stop
          </button>
        ) : (
          <button
            type="submit"
            class={`${button} !border-blue-600 !bg-blue-600 !text-white`}
            disabled={draft.trim() === ""}
          >
            Send
          </button>
        )}
      </form>
      <p class="mx-auto mt-1.5 hidden max-w-2xl text-center text-xs text-stone-500 sm:block">
        Enter sends, Shift+Enter starts a new line
      </p>
    </div>
  );
}

function App() {
  const [history, setHistory] = useState<ChatMessage[]>(loadHistory);
  const [reply, setReply] = useState<Reply | null>(null);
  const [error, setError] = useState<string | null>(null);
  const thread = useRef<HTMLDivElement>(null);

  useEffect(() => {
    localStorage.setItem(storageKey, JSON.stringify(history));
  }, [history]);

  useEffect(() => {
    thread.current!.scrollTop = thread.current!.scrollHeight;
  }, [history, reply]);

  const send = async (text: string) => {
    const messages = [...history, { role: "user", content: text } as const];
    const controller = new AbortController();
    let partial = "";

    setHistory(messages);
    setError(null);
    setReply({ text: "", controller });

    try {
      partial = await streamReply(messages, controller.signal, (streamed) => {
        partial = streamed;
        setReply({ text: streamed, controller });
      });
    } catch (failure) {
      if (!controller.signal.aborted)
        setError(failure instanceof Error ? failure.message : String(failure));
    }

    if (partial !== "") setHistory([...messages, { role: "assistant", content: partial }]);
    setReply(null);
  };

  const clear = () => {
    reply?.controller.abort();
    setHistory([]);
    setError(null);
  };

  return (
    <>
      <header class="flex items-center justify-between gap-4 border-b border-stone-200 bg-white px-4 py-3">
        <h1 class="m-0 text-base font-semibold">chat</h1>
        <button
          type="button"
          class={`${button} text-sm`}
          onClick={clear}
          disabled={history.length === 0 && reply === null}
        >
          New chat
        </button>
      </header>
      <div class="flex-1 overflow-y-auto px-3 py-4 sm:px-4 sm:py-6" ref={thread}>
        <div class="mx-auto flex max-w-2xl flex-col gap-5">
          {history.length === 0 && reply === null && (
            <div class="mt-16 text-center text-stone-500">
              <p class="mb-4">Ask a question, or start from one of these.</p>
              <div class="flex flex-wrap justify-center gap-2">
                {suggestions.map((suggestion) => (
                  <button
                    type="button"
                    key={suggestion}
                    class="cursor-pointer rounded-full border border-stone-200 bg-white px-3.5 py-1.5 text-sm text-stone-900 hover:border-blue-600 hover:text-blue-600"
                    onClick={() => void send(suggestion)}
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          )}
          {history.map((message, index) =>
            message.role === "user" ? (
              <div class="flex justify-end" key={index}>
                <div class="max-w-[85%] whitespace-pre-wrap break-words rounded-2xl rounded-br-sm bg-blue-50 px-3.5 py-2.5">
                  {message.content}
                </div>
              </div>
            ) : (
              <div class="flex" key={index}>
                <div class="bubble min-w-0 max-w-full break-words">
                  <Markdown text={message.content} />
                </div>
              </div>
            ),
          )}
          {reply !== null && (
            <div class="flex">
              <div class="bubble min-w-0 max-w-full break-words">
                {reply.text === "" ? <Typing /> : <Markdown text={reply.text} />}
                {reply.text !== "" && (
                  <span class="cursor ml-0.5 inline-block h-[1em] w-[0.5em] bg-stone-900 align-[-0.15em]" />
                )}
              </div>
            </div>
          )}
          {error !== null && (
            <div class="flex">
              <div class="bubble text-red-700">Something went wrong: {error}</div>
            </div>
          )}
        </div>
      </div>
      <Composer
        busy={reply !== null}
        onSend={(text) => void send(text)}
        onStop={() => reply?.controller.abort()}
      />
    </>
  );
}

document.head.appendChild(Object.assign(document.createElement("style"), { textContent: styles }));
document.body.className = "bg-stone-50 font-sans text-[15px] leading-relaxed text-stone-900";
render(<App />, document.getElementById("app")!);
