/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlatformRouteImport } from './routes/_platform'
import { Route as PlatformIndexRouteImport } from './routes/_platform.index'
import { Route as PlatformLogsRouteImport } from './routes/_platform.logs'
import { Route as PlatformAppletsIndexRouteImport } from './routes/_platform.applets.index'
import { Route as PlatformSettingsIndexRouteImport } from './routes/_platform.settings.index'
import { Route as PlatformSettingsSectionRouteImport } from './routes/_platform.settings.$section'
import { Route as AppletsNameIndexRouteImport } from './routes/applets.$name.index'
import { Route as AppletsNameViewRouteImport } from './routes/applets.$name.$view'

const PlatformRoute = PlatformRouteImport.update({
  id: '/_platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLogsRoute = PlatformLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAppletsIndexRoute = PlatformAppletsIndexRouteImport.update({
  id: '/applets/',
  path: '/applets/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsIndexRoute = PlatformSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformSettingsSectionRoute = PlatformSettingsSectionRouteImport.update({
  id: '/settings/$section',
  path: '/settings/$section',
  getParentRoute: () => PlatformRoute,
} as any)
const AppletsNameIndexRoute = AppletsNameIndexRouteImport.update({
  id: '/applets/$name/',
  path: '/applets/$name/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppletsNameViewRoute = AppletsNameViewRouteImport.update({
  id: '/applets/$name/$view',
  path: '/applets/$name/$view',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PlatformIndexRoute
  '/logs': typeof PlatformLogsRoute
  '/settings/$section': typeof PlatformSettingsSectionRoute
  '/applets/$name/$view': typeof AppletsNameViewRoute
  '/applets/': typeof PlatformAppletsIndexRoute
  '/settings/': typeof PlatformSettingsIndexRoute
  '/applets/$name/': typeof AppletsNameIndexRoute
}
export interface FileRoutesByTo {
  '/logs': typeof PlatformLogsRoute
  '/': typeof PlatformIndexRoute
  '/settings/$section': typeof PlatformSettingsSectionRoute
  '/applets/$name/$view': typeof AppletsNameViewRoute
  '/applets': typeof PlatformAppletsIndexRoute
  '/settings': typeof PlatformSettingsIndexRoute
  '/applets/$name': typeof AppletsNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_platform': typeof PlatformRouteWithChildren
  '/_platform/logs': typeof PlatformLogsRoute
  '/_platform/': typeof PlatformIndexRoute
  '/_platform/settings/$section': typeof PlatformSettingsSectionRoute
  '/applets/$name/$view': typeof AppletsNameViewRoute
  '/_platform/applets/': typeof PlatformAppletsIndexRoute
  '/_platform/settings/': typeof PlatformSettingsIndexRoute
  '/applets/$name/': typeof AppletsNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logs'
    | '/settings/$section'
    | '/applets/$name/$view'
    | '/applets/'
    | '/settings/'
    | '/applets/$name/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logs'
    | '/'
    | '/settings/$section'
    | '/applets/$name/$view'
    | '/applets'
    | '/settings'
    | '/applets/$name'
  id:
    | '__root__'
    | '/_platform'
    | '/_platform/logs'
    | '/_platform/'
    | '/_platform/settings/$section'
    | '/applets/$name/$view'
    | '/_platform/applets/'
    | '/_platform/settings/'
    | '/applets/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlatformRoute: typeof PlatformRouteWithChildren
  AppletsNameViewRoute: typeof AppletsNameViewRoute
  AppletsNameIndexRoute: typeof AppletsNameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_platform': {
      id: '/_platform'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_platform/': {
      id: '/_platform/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/logs': {
      id: '/_platform/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof PlatformLogsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/applets/': {
      id: '/_platform/applets/'
      path: '/applets'
      fullPath: '/applets/'
      preLoaderRoute: typeof PlatformAppletsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/settings/': {
      id: '/_platform/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof PlatformSettingsIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/_platform/settings/$section': {
      id: '/_platform/settings/$section'
      path: '/settings/$section'
      fullPath: '/settings/$section'
      preLoaderRoute: typeof PlatformSettingsSectionRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/applets/$name/': {
      id: '/applets/$name/'
      path: '/applets/$name'
      fullPath: '/applets/$name/'
      preLoaderRoute: typeof AppletsNameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/applets/$name/$view': {
      id: '/applets/$name/$view'
      path: '/applets/$name/$view'
      fullPath: '/applets/$name/$view'
      preLoaderRoute: typeof AppletsNameViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlatformRouteChildren {
  PlatformLogsRoute: typeof PlatformLogsRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
  PlatformSettingsSectionRoute: typeof PlatformSettingsSectionRoute
  PlatformAppletsIndexRoute: typeof PlatformAppletsIndexRoute
  PlatformSettingsIndexRoute: typeof PlatformSettingsIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformLogsRoute: PlatformLogsRoute,
  PlatformIndexRoute: PlatformIndexRoute,
  PlatformSettingsSectionRoute: PlatformSettingsSectionRoute,
  PlatformAppletsIndexRoute: PlatformAppletsIndexRoute,
  PlatformSettingsIndexRoute: PlatformSettingsIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PlatformRoute: PlatformRouteWithChildren,
  AppletsNameViewRoute: AppletsNameViewRoute,
  AppletsNameIndexRoute: AppletsNameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
